repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  name: probot-poc
  description: This repository is to implement settings via probot 
  topics: github, probot
  private: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts:
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        dismissal_restrictions:
          users: []
          teams: []
      restrictions:
        users: []
        teams: []
        apps: []
      allow_force_pushes: true
      allow_deletions: true
      required_linear_history: true
      required_signatures: true
      required_conversation_resolution: true
      lock_branch: true
      allow_bypass_force_push: false
      allow_bypass_pull_request: false
      required_merge_queue: true
