repository:
  default_branch: develop
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: null
      required_linear_history: true
      restrictions:
        users: []
        apps: []
        teams: []

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: null
      required_linear_history: true
      restrictions:
        users: []
        apps: []
        teams: []