# .github/probot.yml

branches:
  - name: master
    protection:
      # required_status_checks:
      #   strict: true
      #   contexts:
      #     - Lint Terraform Code
      #     - Security Check
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        dismissal_restrictions:
          users: []
          teams: []
      restrictions:
        users: []
        teams: []
        apps: []
      allow_force_pushes: true
      allow_deletions: true
      required_linear_history: true
      required_signatures: true
      required_conversation_resolution: true
      lock_branch: true
      allow_bypass_force_push: false
      allow_bypass_pull_request: false
      required_merge_queue: true
